In [ ]:
import numpy as np
import math 
import copy

In [ ]:
start_puzzle = np.array([[7,1,3],
                         [8,2,5],
                         [0,4,6]])

goal_puzzle = np.array([[1,2,3],
                         [4,5,6],
                         [7,8,0]])

no_x = len(start_puzzle)
no_y = len(start_puzzle[0])

In [ ]:
def setup_location_point(puzzle, no_x, no_y):
  location = []
  number_piece = no_x * no_y

  for i in range(0,number_piece):
    location.append([0,0])
  
  return location


def check_location(no_x, no_y, piece, puzzle):
  
  for y in range(0, no_y):
    for x in range(0, no_x):
      if piece == puzzle[x,y]:
        return x, y

def con_to_intplus(value):
  value = math.sqrt(value**2)
  return int(value)


def f_score_func(location, goal_location):
  # g_score
  g_score = 0
  h_score = 0
  for i in range(1, len(location)):
    x = location[i][0] - goal_location[i][0]
    y = location[i][1] - goal_location[i][1]

    x = con_to_intplus(x)
    y = con_to_intplus(y)
    g_score = g_score + x + y
  
    # h_score
    if location[i] != goal_location[i]:
      h_score = h_score + 1


  f_score = g_score + h_score 
  return int(f_score)


def shift(location, location_test ,location_dum, goal_location, puzzle, no_x, no_y):
  sign = 'non'
  
  while True:
    
    print(sign)
    location_space = location[0] ##
    f_score_dum = 99999
    
    
    
    for i in range(0, 4):
      
      if i == 0 and location_space[0] - 1 >= 0 and sign != 'up': # [2, 1]
        shift = copy.copy(location_space)
        shift[0] = shift[0] - 1 ##
    
        
        for i, v in enumerate(location):
          if shift == v:
            location_test = copy.copy(location)
            location_test[i] = location_test[0]
            location_test[0] = shift

            f_score = f_score_func(location_test, goal_location)
           
            if f_score_dum >= f_score:
        

              f_score_dum = f_score
              location_dum = copy.copy(location_test)

              sign_dum = 'down'
              
              puzzle = covert(location_dum, puzzle)

           
      elif i == 1 and location_space[0] + 1 <= no_x - 1 and sign != 'down': # [2, 1]
        shift = copy.copy(location_space)
        shift[0] = shift[0] + 1 ##
     
        for i, v in enumerate(location):
          if shift == v:
            location_test = copy.copy(location)
            location_test[i] = location_test[0]
            location_test[0] = shift
  
            f_score = f_score_func(location_test, goal_location)
          
            if f_score_dum >= f_score:
              
              f_score_dum = f_score
              location_dum = copy.copy(location_test)
              
              sign_dum = 'up'
              
              puzzle = covert(location_dum, puzzle)
         

      elif i == 2 and location_space[1] - 1 >= 0 and sign != 'left': # [2, 1]
        shift = copy.copy(location_space)
        shift[1] = shift[1] - 1 ##

        for i, v in enumerate(location):
          if shift == v:
            location_test = copy.copy(location)
            location_test[i] = location_test[0]
            location_test[0] = shift

            f_score = f_score_func(location_test, goal_location)
           

            if f_score_dum >= f_score:
          
              f_score_dum = f_score
              location_dum = copy.copy(location_test)
              
              sign_dum = 'right'
              
              puzzle = covert(location_dum, puzzle)
      
      elif i == 3 and location_space[1] + 1 <= no_y - 1 and sign != 'right': # [2, 1]
        shift = copy.copy(location_space)
        shift[1] = shift[1] + 1 ##

        for i, v in enumerate(location):
          if shift == v:
            location_test = copy.copy(location)
            location_test[i] = location_test[0]
            location_test[0] = shift

            f_score = f_score_func(location_test, goal_location)
        
            if f_score_dum >= f_score:
              
              f_score_dum = f_score
              location_dum = copy.copy(location_test)
              
              sign_dum = 'left'
              
              puzzle = covert(location_dum, puzzle)

    location = location_dum
    sign = sign_dum
    puzzle = covert(location, puzzle)
    
    print("Next\n ========== \n{0}\n==========\n=====v=====\n=====v=====\n".format(puzzle))
   

    if f_score_dum == 0:
      print("=====End=====")
      break
  return puzzle


def covert(location, puzzle):
  for i ,v in enumerate(location):
    x = location[i][0]
    y = location[i][1]
    puzzle[x,y] = i

  return puzzle



#start
location = setup_location_point(start_puzzle,no_x, no_y)

goal_location = setup_location_point(goal_puzzle,no_x, no_y)

location_dum = setup_location_point(start_puzzle,no_x, no_y)
location_test = setup_location_point(start_puzzle,no_x, no_y)


puzzle = start_puzzle

print("start \n{0}\n\n ======".format(puzzle))

for x in range(0, no_x):
  for y in range(0, no_y):


    location[puzzle[x,y]][0] = check_location(no_x, no_y, puzzle[x,y], puzzle)[0]
    location[puzzle[x,y]][1] = check_location(no_x, no_y, puzzle[x,y], puzzle)[1]

    goal_location[goal_puzzle[x,y]][0] = check_location(no_x, no_y, goal_puzzle[x,y], goal_puzzle)[0]
    goal_location[goal_puzzle[x,y]][1] = check_location(no_x, no_y, goal_puzzle[x,y], goal_puzzle)[1]

  

location_dum = copy.copy(location)
location_test = copy.copy(location)

print(shift(location, location_dum ,location_test, goal_location, puzzle, no_x, no_y))


start 
[[7 1 3]
 [8 2 5]
 [0 4 6]]

non
Next
[[7 1 3]
 [8 2 5]
 [4 0 6]]
=====v=====
=====v=====

left
Next
[[7 1 3]
 [8 2 5]
 [4 6 0]]
=====v=====
=====v=====

left
Next
[[7 1 3]
 [8 2 0]
 [4 6 5]]
=====v=====
=====v=====

down
Next
[[7 1 3]
 [8 0 2]
 [4 6 5]]
=====v=====
=====v=====

right
Next
[[7 1 3]
 [0 8 2]
 [4 6 5]]
=====v=====
=====v=====

right
Next
[[7 1 3]
 [4 8 2]
 [0 6 5]]
=====v=====
=====v=====

up
Next
[[7 1 3]
 [4 8 2]
 [6 0 5]]
=====v=====
=====v=====

left
Next
[[7 1 3]
 [4 0 2]
 [6 8 5]]
=====v=====
=====v=====

down
Next
[[7 1 3]
 [4 2 0]
 [6 8 5]]
=====v=====
=====v=====

left
Next
[[7 1 3]
 [4 2 5]
 [6 8 0]]
=====v=====
=====v=====

up
Next
[[7 1 3]
 [4 2 5]
 [6 0 8]]
=====v=====
=====v=====

right
Next
[[7 1 3]
 [4 2 5]
 [0 6 8]]
=====v=====
=====v=====

right
Next
[[7 1 3]
 [0 2 5]
 [4 6 8]]
=====v=====
=====v=====

down
Next
[[0 1 3]
 [7 2 5]
 [4 6 8]]
=====v=====
=====v=====

down
Next
[[1 0 3]
 [7 2 5]
 [4 6 8]]
=====v=====
=====v=====

left
Next
[[1 2 3]
 

In [3]:
# %cd ~-

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [1]:
%cd drive/MyDrive/

/content/drive/MyDrive


In [2]:
%cd Git_Project/8Puzzle_A*

/content/drive/MyDrive/Git_Project/8Puzzle_A*


In [53]:
# !git clone https://github.com/kimlolipop/8Puzzle_A-.git

Cloning into '8Puzzle_A-'...


In [5]:
!git init

Initialized empty Git repository in /content/drive/My Drive/Git_Project/8Puzzle_A*/.git/


In [4]:
# %cd 8Puzzle_A-

!git remote add origin https://kimlolipop:Kim121139@github.com/kimlolipop/8Puzzle_A-.git
#  !git remote add origin https://<USERNAME>:<PASSWORD>@github.com/<USERNAME>/reponame.git
# # !git remote add origin https://saifullah73:12345@github.com/saifullah73/GitTutorial.git

fatal: not a git repository (or any parent up to mount point /content)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).


In [47]:
!git remote -v

fatal: not a git repository (or any parent up to mount point /content)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).


In [38]:
!git config --global user.email ‘nrtp.dev@gmail.com’
!git config --global user.name ‘kimlolipop’
from getpass import getpass
password = getpass('Password:')

In [61]:
!git add .

In [62]:
!git commit -m 'First commit'

[master (root-commit) ce198a0] First commit
 1 file changed, 1 insertion(+)
 create mode 100644 8Puzzle by A*.ipynb


In [63]:
!git status

On branch master
Your branch is based on 'origin/master', but the upstream is gone.
  (use "git branch --unset-upstream" to fixup)

nothing to commit, working tree clean


In [64]:
!git push

fatal: could not read Username for 'https://github.com': No such device or address
